// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLyXttdbaFBsZh4RS4Vijc22L_FYnPzOE',
    appId: '1:943808137088:web:cee9dc04cd9a27a2b26365',
    messagingSenderId: '943808137088',
    projectId: 'edfmobile-dff21',
    authDomain: 'edfmobile-dff21.firebaseapp.com',
    storageBucket: 'edfmobile-dff21.appspot.com',
    measurementId: 'G-ZRHJVYY1KM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmruzGj2KfLGIRYzqBhH0RyPp3PMsWm6M',
    appId: '1:943808137088:android:53d777367b74919bb26365',
    messagingSenderId: '943808137088',
    projectId: 'edfmobile-dff21',
    storageBucket: 'edfmobile-dff21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7kqKYp-fpEPtJI_Z8ByMlkm5ZD5a8fzM',
    appId: '1:943808137088:ios:1ac2892fe7c383c4b26365',
    messagingSenderId: '943808137088',
    projectId: 'edfmobile-dff21',
    storageBucket: 'edfmobile-dff21.appspot.com',
    iosClientId: '943808137088-afe0pgudp03ghlblt8mddb352u38avie.apps.googleusercontent.com',
    iosBundleId: 'com.example.edf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7kqKYp-fpEPtJI_Z8ByMlkm5ZD5a8fzM',
    appId: '1:943808137088:ios:132868fd2b07aa2eb26365',
    messagingSenderId: '943808137088',
    projectId: 'edfmobile-dff21',
    storageBucket: 'edfmobile-dff21.appspot.com',
    iosClientId: '943808137088-mfosioogf6p6bba81os2pqb8ae6au82h.apps.googleusercontent.com',
    iosBundleId: 'com.example.edf.RunnerTests',
  );
}
